
Training with beta_scale: 1e-05 and penalty_scale: 1e-10
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/share/nklab/users/xz3013/CogModRNN/train_disrnn.py", line 285, in <module>
    main(args_dict,
  File "/share/nklab/users/xz3013/CogModRNN/train_disrnn.py", line 249, in main
    disrnn_params = train_model(args_dict,
  File "/share/nklab/users/xz3013/CogModRNN/train_disrnn.py", line 195, in train_model
    disrnn_params, opt_state, losses = rnn_utils.fit_model(
  File "/share/nklab/users/xz3013/CogModelingRNNsTutorial/CogModelingRNNsTutorial/rnn_utils.py", line 352, in fit_model
    params, opt_state, losses = train_model(
  File "/share/nklab/users/xz3013/CogModelingRNNsTutorial/CogModelingRNNsTutorial/rnn_utils.py", line 272, in train_model
    loss, params, opt_state = train_step(params, opt_state, xs, ys, key_i)
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 3930818960 bytes.