
Training with beta_scale: 1e-05 and penalty_scale: 1e-10



Step 40 of 500; Loss: 1.2352e+05. Model Size: 8802 (Time: 107.4s)
Exception ignored in: <function _xla_gc_callback at 0x2ace0a47da60>
Traceback (most recent call last):
  File "/home/xz3013/.conda/envs/yolanda/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 96, in _xla_gc_callback
    def _xla_gc_callback(*args):
KeyboardInterrupt:
Exception ignored in: <function _xla_gc_callback at 0x2ace0a47da60>
Traceback (most recent call last):
  File "/home/xz3013/.conda/envs/yolanda/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 96, in _xla_gc_callback
    def _xla_gc_callback(*args):
KeyboardInterrupt:
Exception ignored in: <function _xla_gc_callback at 0x2ace0a47da60>
Traceback (most recent call last):
  File "/home/xz3013/.conda/envs/yolanda/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 96, in _xla_gc_callback
    def _xla_gc_callback(*args):

Step 50 of 500; Loss: 1.2351e+05. Model Size: 8802 (Time: 113.3s)
Exception ignored in: <function _xla_gc_callback at 0x2ace0a47da60>
Traceback (most recent call last):
  File "/home/xz3013/.conda/envs/yolanda/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 96, in _xla_gc_callback
    def _xla_gc_callback(*args):
KeyboardInterrupt:
Exception ignored in: <function _xla_gc_callback at 0x2ace0a47da60>
Traceback (most recent call last):
  File "/home/xz3013/.conda/envs/yolanda/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 96, in _xla_gc_callback
    def _xla_gc_callback(*args):
KeyboardInterrupt:
Exception ignored in: <function _xla_gc_callback at 0x2ace0a47da60>
Traceback (most recent call last):
  File "/home/xz3013/.conda/envs/yolanda/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 96, in _xla_gc_callback
    def _xla_gc_callback(*args):
KeyboardInterrupt:
Exception ignored in: <function _xla_gc_callback at 0x2ace0a47da60>
Traceback (most recent call last):
  File "/home/xz3013/.conda/envs/yolanda/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 96, in _xla_gc_callback
    def _xla_gc_callback(*args):
KeyboardInterrupt:
Exception ignored in: <function _xla_gc_callback at 0x2ace0a47da60>
Traceback (most recent call last):
  File "/home/xz3013/.conda/envs/yolanda/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 96, in _xla_gc_callback
    def _xla_gc_callback(*args):
KeyboardInterrupt:
Exception ignored in: <function _xla_gc_callback at 0x2ace0a47da60>
Traceback (most recent call last):
  File "/home/xz3013/.conda/envs/yolanda/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 96, in _xla_gc_callback
    def _xla_gc_callback(*args):
KeyboardInterrupt:
Exception ignored in: <function _xla_gc_callback at 0x2ace0a47da60>
Traceback (most recent call last):
  File "/home/xz3013/.conda/envs/yolanda/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 96, in _xla_gc_callback
    def _xla_gc_callback(*args):
KeyboardInterrupt:
Exception ignored in: <function _xla_gc_callback at 0x2ace0a47da60>
Traceback (most recent call last):
  File "/home/xz3013/.conda/envs/yolanda/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 96, in _xla_gc_callback
    def _xla_gc_callback(*args):

Step 60 of 500; Loss: 1.2351e+05. Model Size: 8802 (Time: 119.2s)
Exception ignored in: <function _xla_gc_callback at 0x2ace0a47da60>
Traceback (most recent call last):
  File "/home/xz3013/.conda/envs/yolanda/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 96, in _xla_gc_callback
    def _xla_gc_callback(*args):

